name: ‚≠ê github-repo-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  github-repo-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Run github-repo-stats
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
