name: ðŸš€ Play Store Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: "17"
  JAVA_DIST: "temurin"

jobs:
  playstore:
    name: Build & Upload to Play Store
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p app
          printf "%s" "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json

      - name: Decode keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ github.workspace }}/release.keystore

      - name: Grant gradlew permission
        run: chmod +x ./gradlew

      - name: Build signed AAB
        env:
          RELEASE_STORE_FILE: ${{ github.workspace }}/release.keystore
          RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundlePlayRelease

      - name: Upload to Play Store (Internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_SERVICE_ACCOUNT_JSON }}
          packageName: com.aditya1875.pokeverse
          releaseFiles: app/build/outputs/bundle/playRelease/app-play-release.aab
          track: internal
          status: completed
